### ISSUE TITLE
tcustommodulename fails in Windows

### ISSUE THREAD

**Issue by juancarlospaco** [yglukhov/nimpy#249] opened 2021-12-29 05:24 UTC
Python versions "2.7", "3.8", "3.9", "3.10" in Windows are failing Tests, they are available in GitHub Actions CI,
the CI is more strict and found bugs in the code for specific Python versions, the error is:

```python
Traceback (most recent call last):
  File "tests\tcustommodulename.py", line 3, in <module>
    import _mycustommodulename

ImportError: DLL load failed while importing _mycustommodulename: The specified module could not be found.

stack trace: (most recent call last)
C:\Users\RUNNER~1\AppData\Local\Temp\nimblecache-0\nimscriptapi_455785573.nim(187, 16)
D:\a\nimpy\nimpy\nimpy.nimble(83, 11) testTask
D:\a\nimpy\nimpy\nimpy.nimble(71, 11) runTests
C:\Users\runneradmin\.choosenim\toolchains\nim-1.6.2\lib\system\nimscript.nim(273, 7) exec
C:\Users\runneradmin\.choosenim\toolchains\nim-1.6.2\lib\system\nimscript.nim(273, 7) Error: unhandled exception: FAILED: python3 tests\tcustommodulename.py [OSError]

running: python3 tests\tcustommodulename.py
Error: Process completed with exit code 1.

```

Looks like Python can not import `_mycustommodulename` module in Windows for some reason.

Add `"2.7", "3.8", "3.9", "3.10"` to the YAML to reproduce the bug.

See https://github.com/yglukhov/nimpy/pull/248

**Comment by yglukhov** [comment] 2022-02-15 11:12
Duplicate of #203

**Closed by yglukhov** 2022-02-15 11:12 UTC

**Comment by juancarlospaco** [comment] 2022-02-15 12:47
But what would be the solution here ?,
maybe add a `when not defined(windows):` to that test ?.

**Comment by yglukhov** [comment] 2022-02-15 14:10
#253

**Comment by juancarlospaco** [comment] 2022-02-15 14:12
Cool!. 🙂:+1:
