### ISSUE TITLE
Nim Version 2.0 breaks (Mac)

### ISSUE THREAD

**Issue by Niminem** [yglukhov/nimpy#293] opened 2023-09-28 04:14 UTC
Hey @yglukhov when I'm only importing the `nimpy` library name, using nim 2.0 on on Mac, and it gives the following error:

/Users/salient/.nimble/pkgs/nimpy-0.2.0/nimpy/py_utils.nim(150, 31) Error: type mismatch: got <PPyObject, PPyObject, typeof(nil)>
but expected one of:
proc (callable_object: PPyObject, args: PPyObject, kw: PPyObject): PPyObject{.cdecl, gcsafe.}

I went back to Nim 1.6.8 and works no problem.

Not quite sure how to fix this

**Comment by yglukhov** [comment] 2023-09-28 07:17
Please provide the source code and the commands to reproduce. And don't have a mac around, and I could not reproduce it with Nim 2.0 on linux, but maybe I missed something.

**Comment by Niminem** [comment] 2023-09-28 15:02
@yglukhov 

Haha yeah the only source code was `import nimpy` and command was `nim c -r test.nim`

It doesn't make sense to me... the type `PPyObject` is a pointer to an object so you should be able to pass `nil` into that proc defined in `py_utils.nim`

**Comment by yglukhov** [comment] 2023-09-28 18:42
> It doesn't make sense to me

Neither to me. Nim 2.0 on linux works just fine with your example. And I can't see how this problem can be platform specific.

**Comment by yglukhov** [comment] 2023-10-30 12:22
It looks a lot like #290. Closing as duplicate.

**Closed by yglukhov** 2023-10-30 12:22 UTC
