### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by qqtop** [yglukhov/nimpy#72] opened 2018-12-03 14:10 UTC
Getting this runtime error
```
nimpy.nim(1004)          pyImport
py_utils.nim(98)         raisePythonError
Error: unhandled exception: <class 'ModuleNotFoundError'>: No module named 'fdb' [Exception]
```
pip3 installed modules are not found anymore , code like pyos=pyImport("os")  work fine
I still have compiled code where this works so not sure if this is a nimpy or Nim issue or something else.
System is debian with python3.6.7 and latest Nim devel

Edit
After further tests on several systems , this error seems to show itself only if there is a mixture of 
python3.7.x standard libraries and python 3.6.x libraries on the system

**Comment by yglukhov** [comment] 2018-12-10 12:44
So it seems you have the package installed into python3.6, but nimpy uses the latest (3.7). You can verify that by inspecting `sys.path`.

**Comment by yglukhov** [comment] 2018-12-10 12:49
Looks like a duplicate of #46

**Closed by yglukhov** 2018-12-10 12:49 UTC
