### ISSUE TITLE
Error: setupForeignThreadGc

### ISSUE THREAD

**Issue by ichux** [yglukhov/nimpy#110] opened 2019-07-18 09:55 UTC
> $ nim --version
Nim Compiler Version 0.20.0 [MacOSX: amd64]

> /usr/local/Cellar/nim/0.20.0/nim/lib/system/gc_common.nim(189, 12) Error: setupForeignThreadGc is available only when ``--threads:on`` and ``--tlsEmulation:off`` are used

**Corrected by**
_nim c --threads:on --tlsEmulation:off --app:lib --out:mymodule.so mymodule_

**Comment by yglukhov** [comment] 2019-08-07 09:00
Can't reproduce. Please provide the exact steps to reproduce: the file you're compiling, and the command line.

**Comment by yglukhov** [comment] 2019-09-22 08:42
No response, closing.

**Comment by lbartoletti** [comment] 2019-11-29 19:48
@yglukhov I reproduce the error on FreeBSD:

```
Nim Compiler Version 1.0.2 [FreeBSD: amd64]
Compiled at 2019-10-27
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

The code is the example on `README.md`

```
nim c --threads:on --app:lib --out:mymodule.so mymodule
```
```
/usr/home/xxx/.nimble/pkgs/nimpy-0.1.0/nimpy.nim(219, 33) template/generic instantiation of `setupForeignThreadGc` from here
/usr/local/lib/system/gc_common.nim(195, 12) Error: setupForeignThreadGc is available only when ``--threads:on`` and ``--tlsEmulation:off`` are used
```

But it can be resolved with this command:

```
nim c --threads:on --tlsEmulation:off --app:lib --out:mymodule.so mymodule
```

Maybe a problem with llvm since macOS and FreeBSD share some resource

**Comment by Benjamin-Lee** [comment] 2019-12-12 01:27
Can confirm on macOS Catalina. I'm compiling a really simple script:

```nim
# squiggle.nim
import nimpy

proc squiggle*(DNA: string): seq[float] {.exportpy.} =
    result = newSeq[float](2 * len(DNA))
    var runningValue = 0.0
    for i, letter in DNA:
        if letter == 'A' or letter == 'a':
            result[i*2] = runningValue + 0.5
            result[(i*2) + 1] = runningValue

        elif letter == 'C' or letter == 'c':
            result[i*2] = runningValue - 0.5
            result[(i*2) + 1] = runningValue

        elif letter == 'T' or letter == 't':
            result[i*2] = runningValue - 0.5
            result[(i*2) + 1] = runningValue - 1
            running_value -= 1

        elif letter == 'G' or letter == 'g':
            result[i*2] = runningValue + 0.5
            result[(i*2) + 1] = runningValue + 1
            running_value += 1
```

with the command 

    nim c --threads:on --app:lib --out:squiggle.pyd squiggle

And getting:
```
Hint: used config file '/usr/local/Cellar/nim/1.0.0/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: squiggle [Processing]
Hint: nimpy [Processing]
Hint: dynlib [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: os [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: complex [Processing]
Hint: sequtils [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: streams [Processing]
Hint: parsejson [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: strscans [Processing]
Hint: py_lib [Processing]
/Users/BenjaminLee/.nimble/pkgs/nimpy-0.1.0/nimpy.nim(221, 33) template/generic instantiation of `setupForeignThreadGc` from here
/usr/local/Cellar/nim/1.0.0/nim/lib/system/gc_common.nim(195, 12) Error: setupForeignThreadGc is available only when ``--threads:on`` and ``--tlsEmulation:off`` are used
```

**Closed** 2019-12-13 10:07 UTC
